postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &default
  database: <%= Rails.application.credentials[Rails.env.to_sym][:db_name] %>
  username: <%= Rails.application.credentials[Rails.env.to_sym][:db_username] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:db_password] %>

development:
  <<: *postgresql
  <<: *default

test:
  <<: *postgresql
  <<: *default
  
production:
  <<: *postgresql
  <<: *default
    
heroku:
  <<: *postgresql
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>